### PR TITLE
neovim better syntax highlighting with neovim-Treesitter

### PR DESCRIPTION
**Pull request by Ciacconas**
- Add Treesitter to the plugin list
For configuration, add languages that don't look good under Treesitter to `disable` list and `additional_vim_regex_highlighting` list
`:TSBufToggle highlight` to check the difference between Treesitter highlighting and neovim-builtin highlighting.

- init.vim
Disabled `syntax enable` to accommodate neovim-Treesitter. 

- xresources.vim
Nearly all Treesitter highlight options are listed, to be easily modified by liking.

### CODE REVIEW

**Comment by flaport** [comment]
Thanks @Ciacconas ,

Overall I think this looks good. 

However, can we change the colors for comments in python/bash/...? I don't like comments to be white. Also for some colorschemes (e.g. nord-white) there's too little contrast.

**Comment by Ciacconas** [comment]
> However, can we change the colors for comments in python/bash/...? I don't like comments to be white.

Yeah can be done, in the xresources.vim file I have all the related highlight groups and the colors listed. For comment, we can simply comment out the the `hi Comment ctermfg=7` it will go back to default, which I think is color 14. 

> Also for some colorschemes (e.g. nord-white) there's too little contrast.

Nord-white looks indeed bad. I never checked nord-white. I was just basically just paid attention to gruvbox, gruvbox-light, and nord. From what I see is that the nord-white low contrast problem can be solve by adjusting the tint of the bright colors of the colorscheme itself. I don't think it has much to do with the vim highlight group though. 

I will try to make some changes to nord-white colors and you can have a look if  that's better. What other colorschemes do you often use i might have a look to them too? For me it was basially gruvbox and gruvbox light.

BTW: how do I update the pull request? or I should just open new one :sweat_smile:

**Comment by Ciacconas** [comment]
Also if you are interested in adjusting some of the highlighting groups more, checkout TreesitterPlayground plugin, add `playground = { enable = true }` to the Treesitter config. Then you can check the highlighting group by `:TSHighlightCapturesUnderCursor`. It is very fun and convinient. :zany_face:

**Comment by flaport** [comment]
Looks awesome. Thanks!

**Pull request merged**
